# Analysis of Experiment 2 Sets

The analysis from this notebook will make up the data shown in Table 4.2.2 (see Paper)

In [1]:
import pandas as pd
import numpy as np

TOTAL_RUNS = 30

#### Analysis of Experiment 2 Set 1
Computation of Mean ± Standard deviation of execution time in milliseconds (ms),nodes expanded,length of path, and optimality ratio

In [3]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set1.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Manhattan,4-dir,50x50,6.519 ± 3.600,627.933 ± 288.055,99.400 ± 0.968,2.028 ± 0.020,100.0%

#### Analysis of Experiment 1 Set 2

In [4]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set2.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Manhattan,8-dir,50x50,1.406 ± 0.482,62.733 ± 6.335,57.200 ± 2.709,1.161 ± 0.061,100.0%

#### Analysis of Experiment 1 Set 3

In [5]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set3.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Euclidean,4-dir,50x50,4.845 ± 2.465,579.433 ± 263.588,101.933 ± 3.183,2.080 ± 0.065,100.0%

#### Analysis of Experiment 1 Set 4

In [6]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set4.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Euclidean,8-dir,50x50,1.038 ± 0.171,75.233 ± 14.388,59.800 ± 2.524,1.220 ± 0.052,100.0%

#### Analysis of Experiment 1 Set 5

In [7]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set5.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Chebyshev,4-dir,50x50,10.677 ± 2.183,1292.333 ± 139.295,100.733 ± 2.664,2.055 ± 0.054,100.0%

#### Analysis of Experiment 1 Set 6

In [8]:
df = df = pd.read_csv("../dataset/sets/experiment_2/exp2_set6.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Heuristic', 'Movement', 'Grid_Size']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Heuristic,Movement,Grid_Size,,,,,
Chebyshev,8-dir,50x50,9.229 ± 1.838,893.400 ± 64.004,57.767 ± 1.569,1.179 ± 0.032,100.0%