# Analysis of Experiment 1 Sets

The analysis from this notebook will make up the data shown in Table 4.1.2 and some of the data in Table 4.3.3  (see Paper)

In [19]:
import pandas as pd
import numpy as np

TOTAL_RUNS = 30

#### Analysis of Experiment 1 Set 1
Computation of Mean ± Standard deviation of density, execution time in milliseconds (ms),nodes expanded,length of path, and memory in bytes (B)

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp2_set1.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
BFS,Small(10x10),Small(10%),0.549 ± 0.472,88.448 ± 3.841,10.517 ± 0.509,4324.966 ± 123.943,96.7%

#### Analysis of Experiment 1 Set 2

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set2.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
BFS,Medium(30x30),Medium(15%),3.842 ± 0.612,765.233 ± 11.855,32.167 ± 0.747,36753.600 ± 564.034,100.0%

#### Analysis of Experiment 1 Set 3

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set3.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
BFS,Large(50x50),Large(20%),13.807 ± 4.161,1996.833 ± 19.402,54.433 ± 1.194,95888.000 ± 949.878,100.0%

#### Analysis of Experiment 1 Set 4

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set4.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
Dijkstra,Small(10x10),Small(10%),0.626 ± 0.217,90.200 ± 3.145,10.733 ± 0.583,4329.600 ± 150.950,100.0%

#### Analysis of Experiment 1 Set 5

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set5.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
Dijkstra,Medium(30x30),Medium(15%),4.736 ± 1.526,765.333 ± 10.357,32.333 ± 0.802,36740.800 ± 487.503,100.0%

#### Analysis of Experiment 1 Set 6

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set6.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
Dijkstra,Large(50x50),Large(20%),14.712 ± 2.367,2003.967 ± 23.442,54.833 ± 1.147,96195.333 ± 1122.066,100.0%

#### Analysis of Experiment 1 Set 7

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set7.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
A*,Small(10x10),Small(10%),0.428 ± 0.299,17.700 ± 8.163,10.600 ± 0.563,2182.400 ± 320.320,100.0%

#### Analysis of Experiment 1 Set 8

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set8.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
A*,Medium(30x30),Medium(15%),1.773 ± 1.106,114.900 ± 51.039,32.067 ± 0.828,9872.000 ± 2466.940,100.0%

#### Analysis of Experiment 1 Set 9

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set9.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
A*,Large(50x50),Large(20%),5.583 ± 1.986,425.345 ± 93.883,55.034 ± 0.944,27074.207 ± 4321.235,96.7%

#### Analysis of Experiment 1 Set 10

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set10.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
D*_Lite,Small(10x10),Small(10%),0.957 ± 0.487,16.733 ± 6.581,10.600 ± 0.563,2152.267 ± 253.666,100.0%

#### Analysis of Experiment 1 Set 11

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set11.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
D*_Lite,Medium(30x30),Medium(15%),4.927 ± 1.781,125.600 ± 49.410,32.133 ± 0.776,10571.267 ± 2154.141,100.0%

#### Analysis of Experiment 1 Set 12

In [ ]:
df = df = pd.read_csv("../dataset/sets/experiment_1/exp1_set12.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Memory_B']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Memory_B,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
D*_Lite,Large(50x50),Large(20%),11.133 ± 3.746,415.966 ± 120.388,54.621 ± 1.083,26963.586 ± 5538.034,96.7%