# Analysis of Experiment 3 Sets

The analysis from this notebook will make up the data for 4-directional Movement model data for experiment 3 shown in Table 4.3.3 (see Paper)

In [1]:
import pandas as pd
import numpy as np

TOTAL_RUNS = 30

#### Analysis of Experiment 3 Set 1
Computation of Mean ± Standard deviation of density, execution time in milliseconds (ms),nodes expanded,length of path, and optimality ratio

In [2]:
df = df = pd.read_csv("../dataset/sets/experiment_3/exp3_set1.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
BFS,50x50,Large(20%),13.453 ± 5.515,1992.560 ± 18.205,99.000 ± 0.000,2.020 ± 0.000,83.3%

#### Analysis of Experiment 3 Set 2

In [5]:
df = df = pd.read_csv("../dataset/sets/experiment_3/exp3_set2.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
Dijkstra,50x50,Large(20%),14.549 ± 3.548,1862.619 ± 153.414,99.952 ± 1.746,2.040 ± 0.036,70.0%

#### Analysis of Experiment 3 Set 3

In [4]:
df = df = pd.read_csv("../dataset/sets/experiment_3/exp3_set3.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
A*,50x50,Large(20%),4.845 ± 2.465,579.433 ± 263.588,101.933 ± 3.183,2.080 ± 0.065,100.0%

#### Analysis of Experiment 3 Set 4

In [3]:
df = df = pd.read_csv("../dataset/sets/experiment_3/exp3_set4.csv")

df = df.replace('NULL', np.nan) 

group_cols = ['Algorithm', 'Grid_Size', 'Density']
metric_cols = ['Execution_Time', 'Nodes_Expanded', 'Path_Length', 'Optimality_Ratio']

for col in metric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Is_Success'] = df[metric_cols].notnull().all(axis=1).astype(int)


stats = df.groupby(group_cols).agg(
    null_count=('Is_Success', lambda x: (x == 0).sum())
)

stats['Success_Rate_%'] = 100 - ((stats['null_count'] / TOTAL_RUNS) * 100)

df_success = df[df['Is_Success'] == 1].copy()
summary = df_success.groupby(group_cols)[metric_cols].agg(['mean', 'std'])

formatted_summary = pd.DataFrame(index=summary.index)
for col in metric_cols:
    formatted_summary[col] = (
        summary[col]['mean'].map('{:.3f}'.format) + 
        " ± " + 
        summary[col]['std'].map('{:.3f}'.format)
    )

formatted_summary['Success_Rate_%'] = stats['Success_Rate_%'].map('{:.1f}%'.format)

# Display final table
display(formatted_summary)

,,,Execution_Time,Nodes_Expanded,Path_Length,Optimality_Ratio,Success_Rate_%
Algorithm,Grid_Size,Density,,,,,
D*_Lite,50x50,Large(20%),10.772 ± 3.518,588.059 ± 119.922,99.941 ± 1.029,2.039 ± 0.021,56.7%